name: VCP-Dest-svk
version: 0.28
abstract: VCP destination driver for svn/svk
author: Chia-liang Kao <clkao@clkao.org>
license: perl
distribution_type: module
requires:
  VCP: 0.9
  SVK: 0.20
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
