abstract: VCP destination driver for svn/svk
author: Chia-liang Kao <clkao@clkao.org>
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: VCP-Dest-svk
no_index: 
  directory: 
    - inc
    - t
requires: 
  SVK: 0.20
  VCP: 0.9
  YAML: 0
version: 0.29
